### ISSUE TITLE
help

### ISSUE THREAD

**Issue by jacGJ** [bclozel/issues-dashboard#11]
![image](https://user-images.githubusercontent.com/32384721/61200367-bc7c7100-a713-11e9-81b8-613e7183350d.png)
it is different from mime!
![image](https://user-images.githubusercontent.com/32384721/61200117-fb5df700-a712-11e9-9014-3d8c89f64a55.png)
can you tell me why? how can I do? thanks!

**Comment by bclozel** [comment]
@jacGJ the auto-completion is available while editing the application.properties file.
It seems you are editing a Java file.

**Comment by bclozel** [comment]
Closing because of lack of feedback on this issue. Please reopen this issue with more information if needed.
