### ISSUE TITLE
Can't access dashboard

### ISSUE THREAD

**Issue by doc-jones** [bclozel/issues-dashboard#13]
Hi, I'm having trouble accessing the dashboard.  And also having trouble with getting the "/" endpoint to work.  The "/events/{projectname} will deliver json, but non of the fields in the dashboard are working.  Here is the message I receive.  
   
`2019-08-14 05:07:49.866 ERROR 19360 --- [io-8443-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class io.spring.demo.issuesdashboard.github.RepositoryEvent]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.spring.demo.issuesdashboard.github.RepositoryEvent`, problem: 'transferred' is not a valid event type
`

Thank you very much for your attention.
Doc

**Comment by bclozel** [comment]
I've update the master branch to ignore unknown event types, as GitHub introduces new event types regularly.
I've also updated this repository with the latest Spring Boot version.
Thanks!
