### ISSUE TITLE
No bean io.micrometer.core.instrument.MeterRegistry

### ISSUE THREAD

**Issue by LorenzoBettini** [bclozel/issues-dashboard#3]
The test io.spring.demo.issuesdashboard.github.GithubClientTests fails after this commit 3ba5e9af489a2e51e36c84d3b399aa8e2d3ad9a8 (and the application cannot correctly start either)

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'githubClient' defined in file [/home/bettini/work/corsi/attsw/code-others/issues-dashboard/target/classes/io/spring/demo/issuesdashboard/github/GithubClient.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.micrometer.core.instrument.MeterRegistry' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

**Comment by sljinlet** [comment]
I'm taking my first look at Spring Boot by way of this example and its accompanying presentation.  I've run into exactly this same problem right off the bat.

It's funny.  This same author was part of a presentation called "It's a Kind of Magic: Under the Covers of Spring Boot".  What's troubling about these "magically do everything for you" frameworks is that one little version change problem or missed line of code, and you get "It's Kinda Magically Broken:  Solution hidden under the covers of Spring Boot".

I tried adding my own implementation of the missing MeterRegistry bean by defining a fresh @Configuration class and a @Bean method that returns a MetricsRegistry object.  I noticed right away that my IDE then complains that there are TWO Beans with the correct type that could be injected into GitHubClient's constructor.  It shows me where the other one is, which was enlightening.  It comes from the spring-boot-actuate.autoconfig library, in the class Metrics
AutoConfiguration.  I see that there's a Bean with the right signature defined there, but it's covered in so much annotation gobbly gook that the old-school XML-file-based Spring app guy that I am can't really make heads or tails of all of it.

If I leave in my own @Bean definition of a MetricsRegistery (inside a @Configuration class), I STILL get the same error message saying that Spring can't find a Bean to inject into GitHubClient, despite there now being a second one that should be available....one that doesn't have any of that extra annotation gobbly gook around it.

I'm new to auto-wiring, so I don't understand what's going on here.  I read that the @SpringBootApplication annotation should turn on all of the autowiring magic.  It seems from what I'm reading that at least my own MetricsRegistry Bean should be getting found and injected.  Similar dependencies seem to be being taken care of ok.

I'm truly stumped.

**Comment by bclozel** [comment]
Hi, sorry I didn't get back to you sooner - for some reason I didn't have notifications enabled on this repository.

I've updated the application to Spring Boot 2.0.3.
To fix this problem, I went ahead and imported the metrics auto-configuration to get the required beans. To improve the test coverage, we could even check that the metrics were reported as part of the client implementation.

**Comment by bhatRV** [comment]
Hello , 
Even I am facing a similar issue with meter Registry , similar exception ,fails to inject meter registry. Can any of you help me how to include this " metrics auto-configuration to get the required beans" in my Code,?
her is the error I am getting : " Unsatisfied dependency expressed through field 'meterRegistry'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.micrometer.core.instrument.MeterRegistry' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}"

**Comment by bclozel** [comment]
@bhatRV are you getting that issue while running the tests? If so, I’ve updated the following file: https://github.com/bclozel/issues-dashboard/blob/master/src/test/java/io/spring/demo/issuesdashboard/github/GithubClientTests.java - check out the annotations on the class here.

**Comment by nikobearrr** [comment]
Hi, I am a bit late to the party and I am not sure if this is the correct place to do so, but I also had the same problem and this github issue was the first on my google search, so I will share what I did. I am running springboot 2.4.0 and micrometer 1.6.1

That was my error: 

`Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.micrometer.graphite.GraphiteConfig' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}`

My particular case was that I did not enable graphite metrics. I added this line to `test/resource/application.properties`:

`management.metrics.export.graphite.enabled=true`

I have that enabled in the `java/resource/application.properties`, but that was not enough. I am not sure if this is the "right" fix, but it worked for me.

**Comment by bclozel** [comment]
This is probably not linked to this issue.

This is probably a typo in your comment but the properties file should be in `src/main/resource/application.properties`.

Feel free to join us on gitter (spring-boot channel) so that we can help you with that.
