### ISSUE TITLE
GITHUB_PROJECT table was NOT created

### ISSUE THREAD

**Issue by roy2020china** [bclozel/issues-dashboard#6]
# Problem Description
## Learn from your Youtube tutorial
1. at  [https://www.youtube.com/watch?v=aA4tfBGY6jY](https://www.youtube.com/watch?v=aA4tfBGY6jY)
2. GITHUB_PROJECT table was created in the tutorial, as shown in the snapshot below:
![screen shot 2019-03-07 at 10 55 31](https://user-images.githubusercontent.com/10363512/53929278-2fbc0980-40c8-11e9-9e99-6a3a90bd057c.png)
Time: 14:50
3. GITHUB_PROJECT table was NOT created during my exercise, as shown in the snapshot below:
![screen shot 2019-03-07 at 10 53 46](https://user-images.githubusercontent.com/10363512/53929352-6a25a680-40c8-11e9-9d39-2ee4e48d3086.png)

# Question: 
How come? 
And how to fix it?
Thank you .

**Comment by bclozel** [comment]
The database is created in memory, not in your local home folder.
You can use the following connection URL on the h2-console: `jdbc:h2:mem:testdb`.

Thanks!
