### ISSUE TITLE
Only health and info actuator endpoints exposed.

### ISSUE THREAD

**Issue by jmdopereiro** [bclozel/issues-dashboard#9]
My understanding from the presentation was that the line

`management.endpoints.web.expose=*`

would make all actuator endpoints available.

When I access https://localhost:8443/actuator/ I only get info and health

I thought it was related with security, but I get this behaviour even after login with admin admin. 

Thanks

**Comment by bclozel** [comment]
Sorry, that was a typo!
This configuration property was changed during the milestone phase and I didn't update the repository accordingly. I've just forced-pushed changes to fix that. You can [get more information about this property in the migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide#endpoints).

Many IDEs support Spring Boot configuration properties as they read the metadata provided with the JARs. In my IDE, the former key was highlighted as it was unknown and would not be bound to the application. This is a really useful feature!

Thanks
